import type { Job } from '@sia/models'
import type { ActivityEvent } from '@/types'

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-001',
    version: 1,
    generated_name: 'Stabilize onboarding flow',
    generated_description: 'Investigate intermittent 400s when creating tenants.',
    status: 'queued',
    priority: 'high',
    order_in_queue: 1,
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    created_by: 'ops-bot',
    updated_by: 'ops-bot',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_input: {
      source: 'gh-issues',
      prompt: 'Tenants occasionally fail creation at /api/orgs.',
    },
    repo_id: 'sia/platform',
    user_acceptance_status: 'not_reviewed',
    user_comments: [],
    confidence_score: '0.81',
    pr_link: '',
  },
  {
    id: 'job-002',
    version: 2,
    generated_name: 'Improve job timeline UI',
    generated_description: 'Add visual indicators for agent progress updates.',
    status: 'queued',
    priority: 'medium',
    order_in_queue: 2,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    created_by: 'product-designer',
    updated_by: 'product-designer',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_input: {
      source: 'slack',
      prompt: 'Hard to tell when Bolt vs Ray touched a job.',
    },
    repo_id: 'sia/web',
    user_acceptance_status: 'not_reviewed',
    user_comments: [],
    confidence_score: '0.74',
    pr_link: '',
  },
  {
    id: 'job-003',
    version: 1,
    generated_name: 'Patch dependency supply alerts',
    generated_description: 'Automatically open CVE tickets above CVSS 7.',
    status: 'in-progress',
    priority: 'high',
    order_in_queue: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    created_by: 'security-bot',
    updated_by: 'bolt',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_input: {
      source: 'gh-issues',
      prompt: 'Automate triage for dependency alerts.',
    },
    repo_id: 'sia/automation',
    user_acceptance_status: 'not_reviewed',
    user_comments: [],
    confidence_score: '0.9',
    pr_link: '',
  },
  {
    id: 'job-004',
    version: 2,
    generated_name: 'Finalize billing PR #812',
    generated_description: 'Resolve final comments on flexible billing rollout.',
    status: 'completed',
    priority: 'medium',
    order_in_queue: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    created_by: 'finance-team',
    updated_by: 'reviewer-1',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_input: {
      source: 'gh-issues',
      prompt: 'Need summarised changelog before rollout.',
    },
    repo_id: 'sia/billing',
    user_acceptance_status: 'reviewed_and_accepted',
    user_comments: [],
    confidence_score: '0.66',
    pr_link: 'https://github.com/sia/billing/pull/812',
  },
  {
    id: 'job-005',
    version: 1,
    generated_name: 'Flaky test remediation',
    generated_description: 'Stabilize account linking e2e suite.',
    status: 'failed',
    priority: 'low',
    order_in_queue: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    created_by: 'qa',
    updated_by: 'ray',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_input: {
      source: 'gh-issues',
      prompt: 'Account linking e2e fails nightly run ~30% of time.',
    },
    repo_id: 'sia/tests',
    user_acceptance_status: 'reviewed_and_asked_rework',
    user_comments: [],
    confidence_score: '0.54',
    pr_link: '',
  },
  {
    id: 'job-006',
    version: 1,
    generated_name: 'Deprecate legacy auth hooks',
    generated_description: 'Remove unused OAuth1 entrypoints and add redirect guard.',
    status: 'archived',
    priority: 'medium',
    order_in_queue: 0,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    created_by: 'platform-core',
    updated_by: 'ops-bot',
    code_generation_logs: undefined,
    code_verification_logs: undefined,
    user_input: {
      source: 'gh-issues',
      prompt: 'Ensure oauth1 callbacks are disabled by default.',
    },
    repo_id: 'sia/platform',
    user_acceptance_status: 'reviewed_and_accepted',
    user_comments: [],
    confidence_score: '0.71',
    pr_link: 'https://github.com/sia/platform/pull/1421',
  },
]

export const MOCK_ACTIVITY_EVENTS: ActivityEvent[] = [
  {
    id: 'activity-001',
    type: 'job_started',
    message: 'Agent Bolt started “Patch dependency supply alerts”.',
    timestamp: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
    jobId: 'job-003',
  },
  {
    id: 'activity-002',
    type: 'job_completed',
    message: 'Job “Finalize billing PR #812” marked as completed.',
    timestamp: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
    jobId: 'job-004',
  },
  {
    id: 'activity-003',
    type: 'job_failed',
    message: 'Job “Flaky test remediation” needs attention.',
    timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    jobId: 'job-005',
  },
]

